"""Report generation service for high-quality downloadable PDF and DOCX reports."""

import io
from datetime import datetime
from typing import Any, Dict, List

# ReportLab imports for PDF generation
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# python-docx imports for Word generation
from docx import Document
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn
from docx.shared import Inches, Pt, RGBColor


# ---------------------------------------------------------------------------
# PDF Report Generation (ReportLab)
# ---------------------------------------------------------------------------

class NumberedCanvas:
    """Canvas wrapper to handle professional page numbering."""

    def __init__(self, *args, **kwargs):
        pass


def generate_pdf_report(data: Dict[str, Any]) -> bytes:
    """
    Generate a professional PDF assessment report from the analysis payload.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=40,
        rightMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    primary_color = colors.HexColor("#0f172a")  # Slate 900
    secondary_color = colors.HexColor("#334155")  # Slate 700
    muted_color = colors.HexColor("#64748b")  # Slate 500
    border_color = colors.HexColor("#cbd5e1")  # Slate 300
    bg_card_color = colors.HexColor("#f8fafc")  # Slate 50
    accent_color = colors.HexColor("#0284c7")  # Sky 600

    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=primary_color,
    )
    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=muted_color,
    )
    section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=primary_color,
        spaceBefore=12,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "BodyTextCustom",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=secondary_color,
    )
    bold_label_style = ParagraphStyle(
        "BoldLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=13,
        textColor=primary_color,
    )
    bullet_style = ParagraphStyle(
        "BulletText",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=secondary_color,
        leftIndent=12,
        firstLineIndent=-12,
    )
    score_big_style = ParagraphStyle(
        "ScoreBig",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=30,
        leading=32,
        textColor=accent_color,
        alignment=1,  # Centered
    )
    score_sub_style = ParagraphStyle(
        "ScoreSub",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=muted_color,
        alignment=1,
    )

    story: List[Any] = []

    # 1. Header
    story.append(Paragraph("SOCIAL MEDIA CONTENT ANALYSIS REPORT", title_style))
    story.append(Paragraph(f"Generated by Social Media Content Analyzer · {datetime.now().strftime('%B %d, %Y, %H:%M')}", subtitle_style))
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=1, color=border_color, spaceBefore=2, spaceAfter=10))

    # 2. Metadata & Score Row
    file_info = data.get("file_info", {})
    score_info = data.get("score", {})
    metrics_info = data.get("metrics", {})
    ai_info = data.get("ai_review", {})

    filename = file_info.get("filename", "Uploaded Content")
    file_type = file_info.get("file_type", "Document").upper()
    method = file_info.get("extraction_method", "Text Extraction")
    total_score = score_info.get("total_score", 0)
    verdict = score_info.get("verdict", "")

    meta_content = [
        [Paragraph("Document / File:", bold_label_style), Paragraph(str(filename), body_style)],
        [Paragraph("Extraction Type:", bold_label_style), Paragraph(f"{file_type} ({method})", body_style)],
        [Paragraph("Analysis Date:", bold_label_style), Paragraph(datetime.now().strftime("%Y-%m-%d %H:%M:%S"), body_style)],
        [Paragraph("AI Engine:", bold_label_style), Paragraph(f"Gemini Structured ({ai_info.get('ai_status', 'active')})", body_style)],
    ]
    meta_table = Table(meta_content, colWidths=[100, 240])
    meta_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
    ]))

    score_box_content = [
        [Paragraph("ENGAGEMENT SCORE", score_sub_style)],
        [Paragraph(f"{total_score}<font size=14 color='#64748b'>/100</font>", score_big_style)],
        [Paragraph("Readiness Heuristic", score_sub_style)],
    ]
    score_box_table = Table(score_box_content, colWidths=[170])
    score_box_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), bg_card_color),
        ("BOX", (0, 0), (-1, -1), 1, border_color),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))

    top_summary_table = Table([[meta_table, score_box_table]], colWidths=[350, 180])
    top_summary_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN", (1, 0), (1, 0), "RIGHT"),
    ]))
    story.append(top_summary_table)

    if verdict:
        story.append(Spacer(1, 6))
        verdict_para = Paragraph(f"<b>Assessment Verdict:</b> {verdict}", body_style)
        verdict_table = Table([[verdict_para]], colWidths=[530])
        verdict_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), bg_card_color),
            ("BOX", (0, 0), (-1, -1), 0.5, border_color),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(verdict_table)

    # 3. Content Metrics Snapshot
    story.append(Spacer(1, 8))
    story.append(Paragraph("CONTENT METRICS SNAPSHOT", section_heading))

    metrics_table_data = [
        [
            Paragraph("<b>Words:</b>", body_style), Paragraph(str(metrics_info.get("word_count", 0)), body_style),
            Paragraph("<b>Characters:</b>", body_style), Paragraph(str(metrics_info.get("character_count", 0)), body_style),
            Paragraph("<b>Sentences:</b>", body_style), Paragraph(str(metrics_info.get("sentence_count", 0)), body_style),
        ],
        [
            Paragraph("<b>Paragraphs:</b>", body_style), Paragraph(str(metrics_info.get("paragraph_count", 0)), body_style),
            Paragraph("<b>Hashtags:</b>", body_style), Paragraph(str(metrics_info.get("hashtag_count", 0)), body_style),
            Paragraph("<b>Mentions:</b>", body_style), Paragraph(str(metrics_info.get("mention_count", 0)), body_style),
        ],
        [
            Paragraph("<b>URLs:</b>", body_style), Paragraph(str(metrics_info.get("url_count", 0)), body_style),
            Paragraph("<b>Questions:</b>", body_style), Paragraph("Yes" if metrics_info.get("has_question") else "None", body_style),
            Paragraph("<b>Readability:</b>", body_style), Paragraph(f"{metrics_info.get('readability_score', 0)} ({metrics_info.get('readability_grade', 'N/A')})", body_style),
        ],
    ]
    m_table = Table(metrics_table_data, colWidths=[80, 95, 80, 95, 80, 100])
    m_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), bg_card_color),
        ("GRID", (0, 0), (-1, -1), 0.5, border_color),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(m_table)

    # 4. Overall Assessment & Core Review
    story.append(Spacer(1, 8))
    story.append(Paragraph("EDITORIAL REVIEW & SEMANTIC ANALYSIS", section_heading))

    overall_text = ai_info.get("overall_assessment", "Analysis not available.")
    story.append(Paragraph(overall_text, body_style))
    story.append(Spacer(1, 6))

    # Strengths & Areas for Improvement side-by-side
    strengths_items = [Paragraph(f"• {s}", bullet_style) for s in ai_info.get("strengths", [])]
    weakness_items = [Paragraph(f"• {w}", bullet_style) for w in ai_info.get("areas_for_improvement", [])]

    if not strengths_items:
        strengths_items = [Paragraph("• No specific strengths highlighted.", bullet_style)]
    if not weakness_items:
        weakness_items = [Paragraph("• No major weaknesses detected.", bullet_style)]

    sw_table_data = [
        [Paragraph("<b>Key Strengths</b>", bold_label_style), Paragraph("<b>Areas for Improvement</b>", bold_label_style)],
        [strengths_items, weakness_items],
    ]
    sw_table = Table(sw_table_data, colWidths=[260, 260])
    sw_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BACKGROUND", (0, 0), (-1, -1), bg_card_color),
        ("BOX", (0, 0), (-1, -1), 0.5, border_color),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, border_color),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(sw_table)

    # 5. Engagement & Dimension Analysis
    story.append(Spacer(1, 8))
    story.append(Paragraph("DIMENSIONAL ENGAGEMENT EVALUATION", section_heading))

    dim_data = [
        [Paragraph("<b>Hook / Opening:</b>", bold_label_style), Paragraph(ai_info.get("hook_analysis", "N/A"), body_style)],
        [Paragraph("<b>Clarity & Cadence:</b>", bold_label_style), Paragraph(ai_info.get("clarity_analysis", "N/A"), body_style)],
        [Paragraph("<b>Engagement Prompts:</b>", bold_label_style), Paragraph(ai_info.get("engagement_analysis", "N/A"), body_style)],
        [Paragraph("<b>Call-to-Action:</b>", bold_label_style), Paragraph(ai_info.get("cta_analysis", "N/A"), body_style)],
        [Paragraph("<b>Audience & Tone:</b>", bold_label_style), Paragraph(f"Tone: {ai_info.get('tone', 'N/A')} — {ai_info.get('audience_analysis', '')}", body_style)],
    ]
    dim_table = Table(dim_data, colWidths=[130, 390])
    dim_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.5, border_color),
        ("BACKGROUND", (0, 0), (0, -1), bg_card_color),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(dim_table)

    # 6. Actionable Recommendations
    suggestions = ai_info.get("suggestions", [])
    if suggestions:
        story.append(Spacer(1, 8))
        story.append(Paragraph("ACTIONABLE RECOMMENDATIONS", section_heading))

        sug_rows = []
        for idx, sug in enumerate(suggestions, start=1):
            title = sug.get("title", f"Recommendation {idx}")
            issue = sug.get("issue", "")
            rec = sug.get("recommendation", "")
            reason = sug.get("reason", "")

            sug_content = [
                Paragraph(f"<b>{idx}. {title}</b>", bold_label_style),
                Paragraph(f"<b>Issue:</b> {issue}", body_style),
                Paragraph(f"<b>Recommendation:</b> {rec}", body_style),
                Paragraph(f"<b>Why it matters:</b> {reason}", subtitle_style),
            ]
            sug_rows.append([sug_content])

        sug_table = Table(sug_rows, colWidths=[520])
        sug_table.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BACKGROUND", (0, 0), (-1, -1), bg_card_color),
            ("BOX", (0, 0), (-1, -1), 0.5, border_color),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, border_color),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(KeepTogether(sug_table))

    # 7. Improved Post Version
    improved_post = ai_info.get("improved_post", "")
    if improved_post:
        story.append(Spacer(1, 8))
        story.append(Paragraph("IMPROVED POST (STRATEGIC REWRITE)", section_heading))

        # Format paragraphs cleanly
        improved_paras = [Paragraph(p.replace("\n", "<br/>"), body_style) for p in improved_post.split("\n\n") if p.strip()]
        improved_table = Table([[improved_paras]], colWidths=[520])
        improved_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), bg_card_color),
            ("BOX", (0, 0), (-1, -1), 1, border_color),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(KeepTogether(improved_table))

    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()


# ---------------------------------------------------------------------------
# DOCX Word Report Generation (python-docx)
# ---------------------------------------------------------------------------

def _set_cell_background(cell, fill_hex: str) -> None:
    """Helper to set background color of a Word table cell."""
    tcPr = cell._element.get_or_add_tcPr()
    shd = parse_xml(f'<w:shd {nsdecls("w")} w:fill="{fill_hex}"/>')
    tcPr.append(shd)


def generate_docx_report(data: Dict[str, Any]) -> bytes:
    """
    Generate a professional Word (.docx) assessment report from the analysis payload.
    """
    doc = Document()

    # Page Margins (0.6 in)
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(0.6)
        section.bottom_margin = Inches(0.6)
        section.left_margin = Inches(0.6)
        section.right_margin = Inches(0.6)

    # Document Title
    title_p = doc.add_paragraph()
    title_run = title_p.add_run("Social Media Content Analysis Report")
    title_run.font.name = "Arial"
    title_run.font.size = Pt(20)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(15, 23, 42)

    sub_p = doc.add_paragraph()
    sub_run = sub_p.add_run(f"Generated by Social Media Content Analyzer · {datetime.now().strftime('%B %d, %Y, %H:%M')}")
    sub_run.font.name = "Arial"
    sub_run.font.size = Pt(9.5)
    sub_run.font.color.rgb = RGBColor(100, 116, 139)

    doc.add_paragraph().paragraph_format.space_after = Pt(4)

    file_info = data.get("file_info", {})
    score_info = data.get("score", {})
    metrics_info = data.get("metrics", {})
    ai_info = data.get("ai_review", {})

    total_score = score_info.get("total_score", 0)
    verdict = score_info.get("verdict", "")

    # Meta & Score Table
    table = doc.add_table(rows=4, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = False

    meta_pairs = [
        ("Document File:", str(file_info.get("filename", "Uploaded File"))),
        ("Extraction Type:", f"{file_info.get('file_type', 'Document').upper()} ({file_info.get('extraction_method', 'Text Extraction')})"),
        ("Engagement Readiness Score:", f"{total_score} / 100 ({score_info.get('disclaimer', '')})"),
        ("AI Status:", f"Gemini Structured ({ai_info.get('ai_status', 'active')})"),
    ]

    for idx, (label, val) in enumerate(meta_pairs):
        row = table.rows[idx]
        cell_lbl, cell_val = row.cells[0], row.cells[1]
        cell_lbl.width = Inches(2.2)
        cell_val.width = Inches(4.8)
        _set_cell_background(cell_lbl, "F1F5F9")
        _set_cell_background(cell_val, "F8FAFC")

        p_lbl = cell_lbl.paragraphs[0]
        r_lbl = p_lbl.add_run(label)
        r_lbl.font.bold = True
        r_lbl.font.size = Pt(9.5)

        p_val = cell_val.paragraphs[0]
        r_val = p_val.add_run(val)
        r_val.font.size = Pt(9.5)

    if verdict:
        doc.add_paragraph().paragraph_format.space_after = Pt(2)
        vp = doc.add_paragraph()
        vr_bold = vp.add_run("Assessment Verdict: ")
        vr_bold.font.bold = True
        vr_bold.font.size = Pt(10)
        vr_text = vp.add_run(verdict)
        vr_text.font.size = Pt(10)

    # Content Metrics Section
    h2 = doc.add_heading("Content Metrics Snapshot", level=2)
    h2.paragraph_format.space_before = Pt(12)
    h2.paragraph_format.space_after = Pt(4)

    m_table = doc.add_table(rows=3, cols=6)
    m_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    m_data = [
        ("Words", str(metrics_info.get("word_count", 0)), "Chars", str(metrics_info.get("character_count", 0)), "Sentences", str(metrics_info.get("sentence_count", 0))),
        ("Paragraphs", str(metrics_info.get("paragraph_count", 0)), "Hashtags", str(metrics_info.get("hashtag_count", 0)), "Mentions", str(metrics_info.get("mention_count", 0))),
        ("URLs", str(metrics_info.get("url_count", 0)), "Questions", "Yes" if metrics_info.get("has_question") else "None", "Readability", f"{metrics_info.get('readability_score', 0)} ({metrics_info.get('readability_grade', 'N/A')})"),
    ]

    for r_idx, row_items in enumerate(m_data):
        row = m_table.rows[r_idx]
        for c_idx in range(6):
            cell = row.cells[c_idx]
            cell.width = Inches(1.16)
            text = row_items[c_idx]
            p = cell.paragraphs[0]
            r = p.add_run(text)
            r.font.size = Pt(9)
            if c_idx % 2 == 0:
                r.font.bold = True
                _set_cell_background(cell, "F1F5F9")
            else:
                _set_cell_background(cell, "F8FAFC")

    # Editorial Review
    h3 = doc.add_heading("Editorial Review & Semantic Analysis", level=2)
    h3.paragraph_format.space_before = Pt(12)
    h3.paragraph_format.space_after = Pt(4)

    p_overall = doc.add_paragraph(ai_info.get("overall_assessment", ""))
    p_overall.paragraph_format.space_after = Pt(6)

    # Strengths
    p_st = doc.add_paragraph()
    r_st = p_st.add_run("Key Strengths:")
    r_st.font.bold = True
    for s in ai_info.get("strengths", []):
        doc.add_paragraph(s, style="List Bullet")

    # Weaknesses
    p_wk = doc.add_paragraph()
    p_wk.paragraph_format.space_before = Pt(4)
    r_wk = p_wk.add_run("Areas for Improvement:")
    r_wk.font.bold = True
    for w in ai_info.get("areas_for_improvement", []):
        doc.add_paragraph(w, style="List Bullet")

    # Actionable Suggestions
    suggestions = ai_info.get("suggestions", [])
    if suggestions:
        h4 = doc.add_heading("Actionable Recommendations", level=2)
        h4.paragraph_format.space_before = Pt(12)
        h4.paragraph_format.space_after = Pt(4)

        for idx, sug in enumerate(suggestions, start=1):
            p_sug = doc.add_paragraph()
            r_num = p_sug.add_run(f"{idx}. {sug.get('title', 'Recommendation')}\n")
            r_num.font.bold = True
            r_num.font.size = Pt(10.5)

            r_iss = p_sug.add_run(f"• Issue: {sug.get('issue', '')}\n")
            r_iss.font.size = Pt(9.5)
            r_rec = p_sug.add_run(f"• Recommendation: {sug.get('recommendation', '')}\n")
            r_rec.font.size = Pt(9.5)
            r_rsn = p_sug.add_run(f"• Why it matters: {sug.get('reason', '')}")
            r_rsn.font.size = Pt(9.5)
            r_rsn.font.italic = True

    # Improved Version
    improved_post = ai_info.get("improved_post", "")
    if improved_post:
        h5 = doc.add_heading("Improved Post (Strategic Rewrite)", level=2)
        h5.paragraph_format.space_before = Pt(12)
        h5.paragraph_format.space_after = Pt(4)

        callout = doc.add_table(rows=1, cols=1)
        callout.alignment = WD_TABLE_ALIGNMENT.CENTER
        callout.rows[0].cells[0].width = Inches(7.0)
        _set_cell_background(callout.rows[0].cells[0], "F8FAFC")

        cp = callout.rows[0].cells[0].paragraphs[0]
        cr = cp.add_run(improved_post)
        cr.font.name = "Arial"
        cr.font.size = Pt(9.5)

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()
